-- ============================================================================
-- Venduo — 0006 ventas: pedidos, líneas y comisiones
--
-- El punto más delicado del modelo. La tasa de comisión se congela al momento
-- de la venta: cambiar el porcentaje de la tienda después no reescribe la
-- historia de nadie.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Pedidos.
--
-- `seller_id` vacío es venta directa por carrito; con valor es venta referida.
-- Un solo flujo de compra, dos modelos de negocio.
--
-- Sin `deleted_at`: un pedido se cancela cambiando su estado, nunca se borra.
-- ----------------------------------------------------------------------------
create table if not exists public.orders (
  id                   uuid primary key default gen_random_uuid(),
  store_id             uuid not null references public.stores(id) on delete cascade,
  order_number         bigint generated by default as identity,

  buyer_name           text not null,
  -- Obligatorio: es el canal por el que se coordina la entrega por WhatsApp.
  buyer_phone          text not null,
  buyer_email          text,

  -- on delete set null, nunca cascade: dar de baja a un vendedor no puede
  -- borrar las ventas de la tienda.
  seller_id            uuid references public.store_sellers(id) on delete set null,
  -- Copia textual del código usado: sobrevive al borrado del vínculo.
  referral_code        text,

  subtotal_cents       integer not null check (subtotal_cents >= 0),
  total_cents          integer not null check (total_cents >= 0),

  -- Congelados al momento de la venta.
  commission_bps       integer not null default 0
                         check (commission_bps between 0 and 10000),
  commission_cents     integer not null default 0 check (commission_cents >= 0),
  net_to_store_cents   integer not null default 0 check (net_to_store_cents >= 0),

  status               public.order_status not null default 'pendiente',
  payment_proof_url    text,
  paid_at              timestamptz,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

create index if not exists orders_store_fecha_idx
  on public.orders (store_id, created_at desc);

-- El panel del vendedor: sus ventas en todas las tiendas donde trabaja.
create index if not exists orders_seller_fecha_idx
  on public.orders (seller_id, created_at desc) where seller_id is not null;

-- ----------------------------------------------------------------------------
-- Líneas del pedido.
--
-- Nombre y precio copiados: si el producto cambia o se da de baja, el pedido
-- sigue diciendo qué se vendió y a cuánto.
--
-- `store_id` repetido a propósito (redundancia deliberada): permite que la
-- política de seguridad sea una comparación sobre esta sola tabla.
-- ----------------------------------------------------------------------------
create table if not exists public.order_items (
  id                uuid primary key default gen_random_uuid(),
  order_id          uuid not null references public.orders(id) on delete cascade,
  store_id          uuid not null references public.stores(id) on delete cascade,
  product_id        uuid references public.products(id) on delete set null,
  product_name      text not null,
  quantity          integer not null check (quantity > 0),
  unit_price_cents  integer not null check (unit_price_cents >= 0),
  created_at        timestamptz not null default now()
);

create index if not exists order_items_order_idx on public.order_items (order_id);
create index if not exists order_items_product_idx on public.order_items (product_id);

-- ----------------------------------------------------------------------------
-- Comisiones.
--
-- `store_id` es anulable y el nombre de la tienda va copiado: cuando se purga
-- una tienda que no se suscribió, la comisión sobrevive y el historial laboral
-- del vendedor queda intacto. Si esto fuera cascada, el día que un emprendedor
-- abandona la plataforma se borraría el antecedente laboral de todos sus
-- vendedores, que es exactamente lo que la plataforma promete no hacer.
-- ----------------------------------------------------------------------------
create table if not exists public.commissions (
  id                 uuid primary key default gen_random_uuid(),
  -- Único: defensa contra el doble conteo si el pedido oscila entre estados.
  order_id           uuid not null unique references public.orders(id) on delete cascade,
  store_id           uuid references public.stores(id) on delete set null,
  store_name         text not null,
  seller_id          uuid references public.store_sellers(id) on delete set null,
  -- Obligatorio y redundante a propósito: evita un join en la política de
  -- seguridad del panel del vendedor.
  seller_user_id     uuid not null references auth.users(id) on delete cascade,

  base_amount_cents  integer not null check (base_amount_cents >= 0),
  rate_bps           integer not null check (rate_bps between 0 and 10000),
  amount_cents       integer not null check (amount_cents >= 0),

  status             public.commission_status not null default 'pendiente',
  payment_reference  text,
  created_at         timestamptz not null default now(),
  confirmed_at       timestamptz,
  paid_at            timestamptz
);

create index if not exists commissions_seller_idx
  on public.commissions (seller_user_id, status);

create index if not exists commissions_store_idx
  on public.commissions (store_id, status);

-- ----------------------------------------------------------------------------
-- Ciclo de vida de la comisión, atado al estado del pedido.
--
-- Al pasar a 'pagado' se crea la comisión con la tasa ya congelada en el
-- pedido. Al cancelarse se anula, nunca se borra.
-- ----------------------------------------------------------------------------
create or replace function public.handle_order_status_change()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  -- Venta cobrada: nace la comisión.
  if new.status = 'pagado' and old.status is distinct from 'pagado'
     and new.seller_id is not null and new.commission_cents > 0 then

    insert into public.commissions (
      order_id, store_id, store_name, seller_id, seller_user_id,
      base_amount_cents, rate_bps, amount_cents, status, confirmed_at
    )
    select
      new.id, new.store_id, s.name, new.seller_id, ss.user_id,
      new.subtotal_cents, new.commission_bps, new.commission_cents,
      'confirmada', now()
    from public.store_sellers ss
    join public.stores s on s.id = new.store_id
    where ss.id = new.seller_id
    on conflict (order_id) do nothing;
  end if;

  -- Venta cancelada: se anula lo que todavía no se pagó y vuelve el stock.
  if new.status = 'cancelado' and old.status is distinct from 'cancelado' then
    update public.commissions
       set status = 'anulada'
     where order_id = new.id
       and status <> 'pagada';

    -- El checkout descontó stock al crear el pedido; acá se devuelve.
    update public.products p
       set stock = p.stock + oi.quantity, updated_at = now()
      from public.order_items oi
     where oi.order_id = new.id
       and oi.product_id = p.id;
  end if;

  return new;
end $$;

drop trigger if exists on_order_status_change on public.orders;
create trigger on_order_status_change
  after update of status on public.orders
  for each row execute function public.handle_order_status_change();
